version: '3.8'

services:
  
  mysql:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: mern_db
    ports:
      - 3307:3306
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api: 
    container_name: api
    build: 
      context: /backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mysql
   