version: '3.8'

services:
  
  mysql:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: mern_db
      DATABASE_URL: mysql://root:rootpwd@mysqldb:3306/mern_db
    ports:
      - 3307:3306
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api: 
    container_name: api
    build: 
      context: /backend
      dockerfile: ./Dockerfile
    ports:
      - 5001:5000
    depends_on:
      - mysql
    networks:
      - api  

  web:
    container_name: web
    build: 
      context: /frontend
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - mysql
      - api
    networks:
      - web

networks:
  api:
  web:
    
   